### PR TITLE
Allow PSR log 2.0

### PR DESCRIPTION
**Pull request by peldax**
Some tweaks in code (type compatibility) may be required.

### CODE REVIEW

**Comment by 0x15f** [comment]
Are there any plans to merge this?

**Comment by willemstuursma** [comment]
Sorry I missed this PR. Are there any further changes required?

**Comment by peldax** [comment]
PSR log 2.0 added parameter types (3.0 added return types), there may be some tweaks required in case of some type juggling, but its unlikely in my option.

**Comment by willemstuursma** [comment]
Superseded by #51.

**Pull request closed without merging**
