### PR TITLE
Code clean up

### PR DESCRIPTION
**Pull request by TheLevti**
- Added php-cs-fixer with a configurable ruleset for code format. Run `vendor/bin/php-cs-fixer fix` to run php-cs-fixer against the .phpcs_dist or .phpcs config. Current configuration is based on PSR-12 plus a few extras.
- Added declare(strict_types=1); to all files to enable strict type checking.
- Fixed a missing log placeholder 2ca1e30.
- Added many missing docblock comments.
- Improved documentation in many classes.
- Improved exception inheritance. All exceptions extend one common project specific interface.
- Fixed package case to support composer 2.0 921622c.

### CODE REVIEW

**Comment by peter279k** [comment]
It looks good, but the commits are very huge messy.

Could you squash them to on commit on this PR?

Thanks.

**Comment by TheLevti** [comment]
Did a little clean up. Unfortunately still 3 commits :)

**Comment by peter279k** [comment]
> Did a little clean up. Unfortunately still 3 commits :)

Hi, thanks for your reply and effort.

Maybe you can refer this [reference](https://github.blog/2016-04-01-squash-your-commits/) to learn about squashing commits on this PR.

**Comment by TheLevti** [comment]
> > Did a little clean up. Unfortunately still 3 commits :)
> 
> Hi, thanks for your reply and effort.
> 
> Maybe you can refer this [reference](https://github.blog/2016-04-01-squash-your-commits/) to learn about squashing commits on this PR.

Thanks, it helped.

**Comment by willemstuursma** [comment]
LGTM!

**Comment by willemstuursma** [comment]
Its a bit weird that CI has not been invoked, I need to look into that.

**Pull request merged**
