### PR TITLE
Fix PHPRedisMutex tests

### PR DESCRIPTION
**Pull request by Furgas**
In PHP Redis extension, closing the connection won't trigger RedisException on further function calls, as it will reconnect and continue to work. This fix makes sure the exception is thrown on closed connection.

### CODE REVIEW

**Comment by willemstuursma** [comment]
Thanks. Is there a test missing for the majority closed connections failure?

**Comment by Furgas** [comment]
AFAIK there is not.

It's strange, because on my machine PHPRedisMutex tests were failing, and I tracked it down to the fact, that `set` and `eval` were still working after closing the connection, hence this pull request. But it seems, that on Travis CI it's not the case, so I'm puzzled now.

If the tests are working for you without this change, then maybe my setup is somewhat broken. Feel free to ditch this PR.

**Comment by willemstuursma** [comment]
I guess it would be better to use mocks for these tests. I'll get back to you on this.

**Comment by Furgas** [comment]
[It seems](https://travis-ci.org/php-lock/lock/jobs/463468547) that I was not delusional after all, but it's somewhat random behaviour.

**Pull request merged**
